// Demo seed — per plan §11. Six-person barkada, designated driver, a non-drinker,
// a messy tab, an old unpaid debt so the ledger shows something, and one member
// who has NOT checked in so the escalation flag is visible. No "test123" anywhere.
import { db } from "./src/db.js";
import { hashPw } from "./src/lib/authz.js";
import { splitExpense } from "../shared/split.js";
import { computeBalances, settle } from "../shared/settle.js";

if (db.prepare("SELECT COUNT(*) c FROM users").get().c > 0) {
  console.log("May data na — i-delete ang uwian.sqlite para mag-seed ulit.");
  process.exit(0);
}

const PW = "BarkadaDemo!2026"; // shared demo password, clearly not test123
const addUser = (name, email, birthdate, can_drink = 1) =>
  db.prepare("INSERT INTO users (name,email,password_hash,birthdate,can_drink) VALUES (?,?,?,?,?)")
    .run(name, email, hashPw(PW), birthdate, can_drink).lastInsertRowid;

const ana   = addUser("Ana Reyes",    "ana@barkada.demo", "1999-04-12");
const ben   = addUser("Ben Cruz",     "ben@barkada.demo", "1998-11-03");
const carl  = addUser("Carl Domingo", "carl@barkada.demo", "2000-01-27");
const dina  = addUser("Dina Flores",  "dina@barkada.demo", "2001-06-15", 0); // non-drinker
const ramon = addUser("Ramon Sy",     "ramon@barkada.demo", "1997-08-22");   // tonight's DD
const ela   = addUser("Ela Villanueva","ela@barkada.demo", "2000-03-09");

const gid = db.prepare("INSERT INTO groups (name,created_by,vouches_required) VALUES ('Barkada Sabado',?,2)")
  .run(ana).lastInsertRowid;
for (const [uid, role] of [[ana, "admin"], [ben, "member"], [carl, "member"], [dina, "member"], [ramon, "member"], [ela, "member"]])
  db.prepare("INSERT INTO group_members (group_id,user_id,role,status) VALUES (?,?,?,'active')").run(gid, uid, role);

const norte = db.prepare("INSERT INTO direction_tags (group_id,label) VALUES (?, 'Norte')").run(gid).lastInsertRowid;
const timog = db.prepare("INSERT INTO direction_tags (group_id,label) VALUES (?, 'Timog')").run(gid).lastInsertRowid;
const tag = (uid, t) => db.prepare("UPDATE group_members SET direction_tag_id=? WHERE group_id=? AND user_id=?").run(t, gid, uid);
tag(ana, norte); tag(ben, norte); tag(carl, timog); tag(dina, timog); tag(ramon, timog); tag(ela, null);

const spot = db.prepare(`INSERT INTO spots (group_id,name,lat,lng,price_range,closes_at,notes,added_by,last_confirmed_at)
  VALUES (?,?,?,?,?,?,?, ?, datetime('now','-70 days'))`) // deliberately stale → shows S5 badge
  .run(gid, "Aling Nena's Ilawan", 14.676, 121.0437, "$$", "02:00",
       "Maganda ang sisig pero mainit ang away sa upuan. May labasan sa likod.", ana).lastInsertRowid;

// ---- previous session with an UNPAID debt (feeds the ledger) ----
const oldSid = db.prepare("INSERT INTO sessions (group_id,spot_id,starts_at,status,designated_driver_id) VALUES (?,?,datetime('now','-14 days'),'closed',?)")
  .run(gid, spot, carl).lastInsertRowid;
{
  const e = db.prepare("INSERT INTO expenses (session_id,paid_by,amount_centavos,description,is_alcohol) VALUES (?,?,?,?,1)")
    .run(oldSid, ben, 24000, "San Miguel 6-pack").lastInsertRowid;
  const shares = splitExpense(24000, [String(ana), String(ben), String(carl)]);
  for (const [u, s] of Object.entries(shares))
    db.prepare("INSERT INTO expense_participants (expense_id,user_id,share_centavos) VALUES (?,?,?)").run(e, u, s);
  const transfers = settle(computeBalances([{ id: e, paid_by: ben, amount_centavos: 24000 }], { [e]: shares }));
  for (const t of transfers)
    db.prepare("INSERT INTO settlements (session_id,from_user,to_user,amount_centavos,status) VALUES (?,?,?,?,'open')")
      .run(oldSid, t.from, t.to, t.amount_centavos);
  // mark it as generated by close-tab round 1 (already 'closed' above)
}

// ---- tonight's messy session ----
// deadline already passed by 75 min → escalation flag is visible in the demo
const sid = db.prepare(`INSERT INTO sessions (group_id,spot_id,starts_at,status,designated_driver_id,uwian_deadline)
  VALUES (?,?,datetime('now','+1 hour'),'wrapped',?,datetime('now','-75 minutes'))`)
  .run(gid, spot, ramon).lastInsertRowid;

const rsvp = (uid, st) => db.prepare("INSERT INTO rsvps (session_id,user_id,status) VALUES (?,?,?)").run(sid, uid, st);
[ana, ben, carl, dina, ramon].forEach((u) => rsvp(u, "going"));
rsvp(ela, "maybe");

const addExp = (paid_by, pesos, desc, alcohol, parts) => {
  const cents = Math.round(pesos * 100);
  const e = db.prepare("INSERT INTO expenses (session_id,paid_by,amount_centavos,description,is_alcohol) VALUES (?,?,?,?,?)")
    .run(sid, paid_by, cents, desc, alcohol).lastInsertRowid;
  const shares = splitExpense(cents, parts.map(String));
  for (const [u, s] of Object.entries(shares))
    db.prepare("INSERT INTO expense_participants (expense_id,user_id,share_centavos) VALUES (?,?,?)").run(e, u, s);
};
addExp(ana, 450, "Beer bucket (12)", 1, [ana, ben, carl, ela]);            // dina + ramon excluded automatically
addExp(ben, 320, "Pulutan: sisig + puto", 0, [ana, ben, carl, dina, ramon, ela]); // everyone shares food
addExp(carl, 450, "Extra round ni Ben (binayaran ni Carl)", 1, [ben, carl, ana]);  // second-round forgotten-no-more
addExp(ramon, 150, "Softdrinks at yelo", 0, [ana, ben, carl, dina, ramon, ela]);
addExp(dina, 200, "Cash-in-hand sa iniligtas na grab (bayad na)", 0, [dina]); // payer-only → zero balance, already settled

// buddy pairs per direction tag (Norte: ana+ben, Timog: carl+dina+ramon trio, ela pending)
db.prepare("INSERT INTO buddy_pairs (session_id,user_a,user_b) VALUES (?,?,?)").run(sid, ana, ben);
db.prepare("INSERT INTO buddy_pairs (session_id,user_a,user_b,user_c) VALUES (?,?,?,?)").run(sid, carl, dina, ramon);

// check-ins: everyone home EXCEPT Ela (who said maybe but showed up) → flag stage 3 visible
const ci = (uid, mode) => db.prepare("INSERT INTO checkins (session_id,user_id,mode,home_confirmed_at) VALUES (?,?,?,datetime('now'))").run(sid, uid, mode);
ci(ana, "jeep"); ci(ben, "grab"); ci(carl, "walk"); ci(dina, "friend_drive"); ci(ramon, "own_drive");
db.prepare("INSERT INTO checkins (session_id,user_id,flag_stage) VALUES (?,?,?)").run(sid, ela, 3);

// tonight's tab is closed with settlements so the Settle-up screen demos live
{
  const { expenses, shares } = { expenses: db.prepare("SELECT * FROM expenses WHERE session_id=?").all(sid),
    shares: Object.fromEntries(db.prepare("SELECT * FROM expenses WHERE session_id=?").all(sid).map((e) => [e.id,
      Object.fromEntries(db.prepare("SELECT user_id, share_centavos FROM expense_participants WHERE expense_id=?").all(e.id).map((r) => [String(r.user_id), r.share_centavos]))])) };
  for (const t of settle(computeBalances(expenses, shares)))
    db.prepare("INSERT INTO settlements (session_id,from_user,to_user,amount_centavos,status) VALUES (?,?,?,?,'open')")
      .run(sid, t.from, t.to, t.amount_centavos);
  db.prepare("UPDATE sessions SET status='wrapped', closed_tab_at=datetime('now','-20 minutes') WHERE id=?").run(sid);
}

// demo variety: one transfer mid-confirmation, one disputed (admin sees note)
{
  const openT = db.prepare("SELECT * FROM settlements WHERE session_id=? AND status='open' ORDER BY id").all(sid);
  if (openT.length >= 2) {
    db.prepare("UPDATE settlements SET status='paid_claimed' WHERE id=?").run(openT[0].id);
    db.prepare("UPDATE settlements SET status='disputed', note=? WHERE id=?")
      .run("Parang hindi ganito karami share ko, tignan mo ulit.", openT[1].id);
  }
}

// hangganan rows exist but are owner-only via API; seed two privately
db.prepare("INSERT INTO limit_counters (session_id,user_id,lim,count) VALUES (?,?,?,?)").run(sid, ben, 5, 4); // approaching
db.prepare("INSERT INTO limit_counters (session_id,user_id,lim,count) VALUES (?,?,?,?)").run(sid, ana, 4, 1);

// notifications to show escalation state
db.prepare("INSERT INTO notifications (user_id,kind,payload) VALUES (?,?,?)")
  .run(ana, "escalation", JSON.stringify({ session_id: sid, user_id: ela, message: "Wala pa ring balita si Ela. Buddy: hingiin ng update." }));

console.log(`Seeded. group=${gid} old_session=${oldSid} session=${sid} spot=${spot}`);
console.log(`Logins: ana@barkada.demo … ela@barkada.demo / pw: ${PW}`);
